# Generated by Django 2.2.5 on 2019-09-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyPredictResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offertype', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('area', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('age', models.IntegerField()),
                ('price1', models.BigIntegerField()),
                ('price2', models.BigIntegerField()),
                ('responseDate', models.DateTimeField()),
                ('firstdata', models.DateTimeField()),
                ('lastdata', models.DateTimeField()),
                ('filtering', models.CharField(max_length=50)),
                ('recordcount', models.IntegerField()),
            ],
        ),
    ]
