# Generated by Django 2.2.5 on 2019-09-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryhandler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertypredictresponse',
            name='firstdata',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='propertypredictresponse',
            name='lastdata',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='propertypredictresponse',
            name='price1',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='propertypredictresponse',
            name='price2',
            field=models.BigIntegerField(null=True),
        ),
    ]
