# Generated by Django 2.2.5 on 2019-09-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryhandler', '0002_auto_20190925_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertypredictresponse',
            name='firstdata',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertypredictresponse',
            name='lastdata',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertypredictresponse',
            name='price1',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertypredictresponse',
            name='price2',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
