# Generated by Django 2.2.5 on 2019-09-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryhandler', '0003_auto_20190925_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertypredictresponse',
            name='isithot',
            field=models.IntegerField(default=0),
        ),
    ]
