# Generated by Django 2.2.5 on 2019-10-01 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queryhandler', '0004_propertypredictresponse_isithot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertypredictresponse',
            old_name='price1',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='propertypredictresponse',
            name='price2',
        ),
    ]
