# Generated by Django 2.2.5 on 2019-10-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryhandler', '0005_auto_20191001_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertypredictresponse',
            name='propertytype',
            field=models.CharField(choices=[('RES', 'مسکونی'), ('COM', 'اداری-تجاری'), ('IND', 'صنعتی')], default='RES', max_length=3),
        ),
    ]
