# Generated by Django 2.2.4 on 2019-09-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0002_scrapelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scrape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('resultnumber', models.IntegerField()),
                ('scrapetype', models.CharField(max_length=20)),
                ('site', models.CharField(max_length=255)),
                ('baselink', models.CharField(max_length=255)),
                ('currentlink', models.CharField(max_length=255)),
                ('pagenumber', models.IntegerField()),
                ('pagetarget', models.IntegerField()),
                ('currnetrecord', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='ScrapeLog',
        ),
    ]
