# Generated by Django 2.2.4 on 2019-09-13 11:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0003_auto_20190909_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyfile',
            name='publishdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
