# Generated by Django 2.2.4 on 2019-09-13 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0004_propertyfile_publishdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrape',
            name='currnetrecord',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scrape',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='scrape',
            name='pagenumber',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='scrape',
            name='pagetarget',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='scrape',
            name='site',
            field=models.CharField(default='ihome', max_length=255),
        ),
        migrations.AlterField(
            model_name='scrape',
            name='status',
            field=models.CharField(default=datetime.datetime.now, max_length=20),
        ),
    ]
