# Generated by Django 2.2.5 on 2019-09-14 07:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0007_auto_20190914_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrape',
            name='last_update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scrape',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 14, 7, 30, 59, 752803, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scrape',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 14, 7, 30, 59, 578398, tzinfo=utc)),
        ),
    ]
