# Generated by Django 2.2.5 on 2019-09-15 14:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0009_auto_20190914_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrape',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 15, 14, 33, 54, 262836, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scrape',
            name='last_update_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 15, 14, 33, 54, 263004, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scrape',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 15, 14, 33, 53, 26894, tzinfo=utc)),
        ),
    ]
