# Generated by Django 2.2.5 on 2019-09-15 15:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0010_auto_20190915_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrape',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 15, 15, 8, 38, 478624, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scrape',
            name='last_update_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 15, 15, 8, 38, 478799, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scrape',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 15, 15, 8, 38, 371069, tzinfo=utc)),
        ),
    ]
