# Generated by Django 2.2.5 on 2019-10-01 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0013_auto_20190917_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyfile',
            old_name='price1',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='propertyfile',
            name='price2',
        ),
    ]
