# Generated by Django 2.2.5 on 2019-10-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0014_auto_20191001_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyfile',
            name='propertytype',
            field=models.CharField(choices=[('RES', 'مسکونی'), ('COM', 'اداری-تجاری'), ('IND', 'صنعتی')], default='RES', max_length=3),
        ),
        migrations.AddField(
            model_name='scrape',
            name='propertytype',
            field=models.CharField(choices=[('RES', 'مسکونی'), ('COM', 'اداری-تجاری'), ('IND', 'صنعتی')], default='RES', max_length=3),
        ),
    ]
