# Generated by Django 2.2.4 on 2019-08-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offertype', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('area', models.IntegerField()),
                ('price1', models.BigIntegerField()),
                ('price2', models.BigIntegerField()),
                ('rooms', models.IntegerField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
