# Generated by Django 2.2.4 on 2019-09-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='activationcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=28)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
