# Generated by Django 2.2.4 on 2019-09-09 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_activationcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyFile',
        ),
    ]
